package kirjarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 10:14:46 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KirjaTest {


  // Generated by ComTest BEGIN
  /** testGetNimi84 */
  @Test
  public void testGetNimi84() {    // Kirja: 84
    Kirja tennis = new Kirja(); 
    tennis.taytaTiedoillaTennis(); 
    { String _l_=tennis.getNimi(),_r_="Tennisesseet"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 87" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi99 */
  @Test
  public void testRekisteroi99() {    // Kirja: 99
    Kirja tennis = new Kirja(); 
    assertEquals("From: Kirja line: 101", 0, tennis.getTunnusNro()); 
    tennis.rekisteroi(); 
    Kirja tennis2 = new Kirja(); 
    tennis2.rekisteroi(); 
    int n1 = tennis.getTunnusNro(); 
    int n2 = tennis2.getTunnusNro(); 
    assertEquals("From: Kirja line: 107", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString160 */
  @Test
  public void testToString160() {    // Kirja: 160
    Kirja k = new Kirja(); k.taytaTiedoillaTennis(); 
    Kirja s = new Kirja(); s.taytaTiedoillaTennis(); 
    assertEquals("From: Kirja line: 163", true, k.toString().equals(s.toString())); 
    k.setTunnusNro(6); 
    assertEquals("From: Kirja line: 165", false, k.toString().equals(s.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone307 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone307() throws CloneNotSupportedException {    // Kirja: 307
    Kirja mer = new Kirja(); 
    mer.parse("   2   |  10  |   158  | 12.1.2022 | 14.1.2022 | kissa "); 
    Kirja kopio = mer.clone(); 
    assertEquals("From: Kirja line: 312", mer.toString(), kopio.toString()); 
    mer.parse("   1   |  11  |  1122  | 19.1.2000 | 1.1.2100 | koira "); 
    assertEquals("From: Kirja line: 314", false, kopio.toString().equals(mer.toString())); 
  } // Generated by ComTest END
}