package kirjarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.04 19:36:09 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KirjanmerkkiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi57 */
  @Test
  public void testRekisteroi57() {    // Kirjanmerkki: 57
    Kirjanmerkki merkki = new Kirjanmerkki(); 
    assertEquals("From: Kirjanmerkki line: 59", 0, merkki.getTunnusNro()); 
    merkki.rekisteroi(); 
    var merkki2 = new Kirjanmerkki(); 
    merkki2.rekisteroi(); 
    int n1 = merkki.getTunnusNro(); 
    int n2 = merkki2.getTunnusNro(); 
    assertEquals("From: Kirjanmerkki line: 65", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone228 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone228() throws CloneNotSupportedException {    // Kirjanmerkki: 228
    Kirjanmerkki mer = new Kirjanmerkki(); 
    mer.parse("   2   |  10  |   158  | 12.1.2022 | 14.1.2022 | kissa "); 
    Kirjanmerkki kopio = mer.clone(); 
    assertEquals("From: Kirjanmerkki line: 233", mer.toString(), kopio.toString()); 
    mer.parse("   1   |  11  |  1122  | 19.1.2000 | 1.1.2100 | koira "); 
    assertEquals("From: Kirjanmerkki line: 235", false, kopio.toString().equals(mer.toString())); 
  } // Generated by ComTest END
}