package kirjarekisteri.test;
// Generated by ComTest BEGIN
import java.util.List;
import static org.junit.Assert.*;
import org.junit.*;
import kirjarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.07 10:16:07 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KirjarekisteriTest {


  // Generated by ComTest BEGIN
  /** testAnnaMerkit59 */
  @Test
  public void testAnnaMerkit59() {    // Kirjarekisteri: 59
    Kirjarekisteri rekisteri = new Kirjarekisteri(); 
    Kirja kz = new Kirja(), kz1 = new Kirja(), kz2 = new Kirja(); 
    kz.rekisteroi(); kz1.rekisteroi(); kz2.rekisteroi(); 
    int id1 = kz.getTunnusNro(); 
    int id2 = kz1.getTunnusNro(); 
    Kirjanmerkki tennis = new Kirjanmerkki(id1); rekisteri.lisaa(tennis); 
    Kirjanmerkki tennis2 = new Kirjanmerkki(id2); rekisteri.lisaa(tennis2); 
    List<Kirjanmerkki> loytyneet; 
    loytyneet = rekisteri.annaMerkit(kz2); 
    assertEquals("From: Kirjarekisteri line: 71", 0, loytyneet.size()); 
    loytyneet = rekisteri.annaMerkit(kz); 
    assertEquals("From: Kirjarekisteri line: 73", 1, loytyneet.size()); 
  } // Generated by ComTest END
}