package fxKirjat.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxKirjat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.04 21:06:24 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class FxKirjatMainTest {
}